package Problem2Completed;
/*Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

import java.util.ArrayList;
import java.util.Arrays;

public class Main {
    public static void main(String[] args) {

        ArrayList<Integer> fibonacci = new ArrayList<>(Arrays.asList(1, 2));
        for (int i = 2; i < 50; i++) {
            if (fibonacci.get(i - 2) + fibonacci.get(i - 1) <= 4000000) {
                fibonacci.addLast(fibonacci.get(i - 2) + fibonacci.get(i - 1));
            } else {
                i = 50;
            }
        }
        System.out.println(fibonacci);

        int sum = 0;
        for (Integer fibonacco : fibonacci) {
            if (fibonacco % 2 == 0) {
                sum += fibonacco;
            }
        }
        System.out.println(sum);
    }
}
