package problem_12_completed;
/*Highly Divisible Triangular Number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +
2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

        1 : 1
        3 : 1, 3
        6 : 1, 2, 3, 6
        10 : 1, 2, 5, 10
        15 : 1, 3, 5, 15
        21 : 1, 3, 7, 21
        28 : 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?*/

public class Main {

    public static int getNumberOfDivisors(int n) {

        int divisors = 0;
        for (int x = 1; x <= (int) Math.sqrt(n); x++) {
            if (n % x == 0) {
                divisors += 2;
            }
        }
        return divisors;
    }

    public static void main(String[] args) {

        int number = 0;
        int numberOfDivisors = 0;
        for (int i = 1; i < 15000; i++) {
            number = 0;
            for (int j = 1; j <= i; j++) {
                number += j;
            }

            numberOfDivisors = getNumberOfDivisors(number);
            if (numberOfDivisors > 500) {
                break;
            }
        }
        System.out.println(number);
        System.out.println(numberOfDivisors);
    }
}
